FROM golang AS builder
MAINTAINER com.pulse

WORKDIR /app
COPY . /app

RUN go get github.com/swaggo/swag/cmd/swag
RUN go install . && \
    go build -ldflags "-s -w"

FROM scratch
COPY --from=builder /app/go-version-manager /
CMD ["/go-version-manager"]
EXPOSE 8000